name: build-lint-test

on:
  pull_request:
    branches:
      - main

# env:

jobs:
  build-lint-test:
    strategy:
      fail-fast: true
      matrix:
        version:
          - "8"
          - "9"

    runs-on: ubuntu-latest
    steps:

      # checkout

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # run tests

      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: |
          npm i \
            @nestjs/common@${{ matrix.version }} \
            @nestjs/core@${{ matrix.version }} \
            @nestjs/cqrs@${{ matrix.version }} \
            @nestjs/platform-express@${{ matrix.version }} \
            -D
      - run: npm run lint
      - run: npm t
      - run: npm run build
