name: on-push

on:
  push:
    branches:
      - '**/*'

# env:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      # checkout

      - uses: actions/checkout@v3

      # run tests

      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm run lint
      - uses: actions/cache@v3
        with:
          path: coverage
          key: ${{ github.sha }}
      - run: npm t
      - run: npm run build

  publish:
    if: github.ref == 'refs/heads/main' && github.actor != 'dependabot[bot]' && github.actor != 'mergify[bot]'
    runs-on: ubuntu-latest
    needs:
      - test
    steps:

      # checkout

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # push test coverage

      - uses: actions/cache@v3
        with:
          path: coverage
          key: ${{ github.sha }}
      - uses: paambaati/codeclimate-action@v2.7.5
        with:
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}

      # build and publish

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm version --no-git-tag-version $(git describe --abbrev=0 --tags)-alpha.$(git rev-parse --short=6 ${{ github.sha }}) || true
      - run: npm publish --tag alpha || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
